services:
#----------------------------------
# Database service configuration
#----------------------------------
  db:
    image: mysql:8.0
    container_name: systeme_parquet_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - systeme_parquet_network
#---------------------------------
# phpMyAdmin service configuration
#---------------------------------

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: systeme_parquet_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    ports:
      - "8081:80"
    networks:
      - systeme_parquet_network

volumes:
  db_data:

networks:
  systeme_parquet_network:
    driver: bridge
